# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "bam_call_variant_all"
description: The subworkflow implements SNV and indel variant calling using the lofreq variant caller. In brief, the workflow takes a set of aligned reads (BAM), normalizes and annotates the alignments, performs probabilistic variant calling and returns a raw set of variants (VCF).
keywords:
  - variant calling
  - variant
  - calling
  - bam
  - vcf
components:
  - lofreq/viterbi
  - lofreq/indelqual
  - lofreq/callparallel
  - samtools/index
## TODO nf-core: List all of the channels used as input with a description and their structure
input:
  - ch_bam:
      type: map
      description: |
        Groovy Map containing sample information and a corresponding read alignment file (BAM)
        Structure: [ val(meta), path(bam) ]
  - ch_ref:
      type: file
      description: |
        File in (multi) FASTA format containing reference sequences
      pattern: "*.{fasta/fa}"
  - ch_ref_index:
      type: file
      description: |
        Index file for the reference sequences
      pattern: "*.{fai}"
output:
  - bam:
      type: map
      description: |
        Groovy Map containing sample information and a corresponding read alignment file (BAM).
        Copy of the original input alignments but normalized, sorted and annotated for variant calling.
        Structure: [ val(meta), path(bam) ]
      pattern: "*.bam"
  - bai:
      type: map
      description: |
        Groovy Map containing sample information and a corresponding read alignment index file (BAI).
        Structure: [ val(meta), path(bai) ]
      pattern: "*.bai"
  - vcf:
      type: map
      description: |
        Groovy Map containing sample information and a corresponding set of raw variant calls (VCF).
        Structure: [ val(meta), path(csi) ]
      pattern: "*.vcf"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@Krannich479"
maintainers:
  - "@Krannich479"
