name: PREPARE_REFERENCE
description: format the fasta file
keywords:
  - fasta
  - reference
  - formatting
tools:
  - Biopython:
      description: |
        replace special and non-standard characters for compatibility purposes
      homepage: https://github.com/biopython/biopython
      documentation: https://biopython.org/wiki/Documentation
      doi: https://doi.org/10.1093/bioinformatics/btp163
      licence: ["Biopython License Agreement","BSD 3-Clause License"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA file
      pattern: "*.{fasta/fa}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: adjusted FASTA file
      pattern: "*.{fasta}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@DimitriTernovoj"
maintainers:
  - "@DimitriTernovoj"
