name: INV_CREATE_CONSENSUS_MASK_BEDTOOLS
description: infer low coverage regions, remove all regions containing deletions and concatenate it with another bed file
keywords:
  - genome coverage
  - mask
tools:
  - bedtools:
      description: |
        infer low coverage regions, remove all regions containing deletions
      homepage: https://github.com/arq5x/bedtools2
      documentation: https://bedtools.readthedocs.io/en/latest/#
      doi: 10.1093/bioinformatics/btq033
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: VCF file
      pattern: "*.{vcf}"
  - bam:
      type: file
      descrition: BAM file
      pattern: "*.{bam}"
  - bed:
      type: file
      descrition: BED file
      pattern: "*.{bed}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bed:
      type: file
      description: bed file
      pattern: "*.{bed}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@DimitriTernovoj"
maintainers:
  - "@DimitriTernovoj"
