name: ADJUST_GT_CONSENSUS
description: Add and adjust Genotypes, index the vcf
keywords:
  - vcf
  - consensus
  - genotype
tools:
  - bcftools index and +setGT:
      description: |
        index a vcf file
        set the genotype based on a defined condition
      homepage: http://samtools.github.io/bcftools/bcftools.html
      documentation: http://www.htslib.org/doc/bcftools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
  - custom bash script:
      description: |
        add a GT column, add a line containing meta-information
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: VCF file
      pattern: "*.{vcf}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: VCF file with added and adjusted GT column
      pattern: "*.{vcf}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@DimitriTernovoj"
maintainers:
  - "@DimitriTernovoj"
