name: KMA
description: Aligning reads to a DB via KMA alignment
keywords:
  - fastq
  - alignment
  - kma
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information. Requires 'id' key to be present if no custom prefix parameter is specified.
        e.g. [ id:'sample' ]
  - reads:
      type: file
      description: FASTQ file
      pattern: "*.{fastq,fq}"
  - meta2:
      type: map
      description: |
        Groovy Map containing reference index information. Requires 'id' key to be present if no custom prefix parameter is specified.
        e.g. [ id:'reference' ]
  - index:
      type: file
      description: kma database file generated via kma_index
      pattern: "*.{db}"
  - interleaved:
      type: boolean
      description: use one interleaved fastq file (true) or two paired fastq files (false)
      pattern: "true or false"
  - mat_format:
      type: boolean
      description: generate additional matrix file (true) or not (false)
      pattern: "true or false"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'reference' ]
  - res:
      type: file
      description: A result overview giving the most common statistics for each mapped template.
      pattern: "*.{res}"
  - fsa:
      type: file
      description: The consensus sequences drawn from the alignments.
      pattern: "*.{fsa}"
  - aln:
      type: file
      description: The consensus alignment of the reads against their template.
      pattern: "*.{aln}"
  - frag:
      type: file
      description: Mapping information on each mapped read, where the columns are read, number of equally well mapping templates, mapping score, start position, end position (w.r.t. template), the choosen template.
      pattern: "*.{frag.gz}"
  - mat:
      type: file
      description: Base counts on each position in each template, (only if -matrix is enabled).
      pattern: "*.{mat.gz}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@Krannich479"
maintainers:
  - "@Krannich479"
