name: KMA_INDEX
description: Creates a database file for KMA alignment
keywords:
  - fasta
  - index
  - kma
input:
  - meta:
      type: map
      description: |
        Groovy Map containing reference information
        e.g. [ id:'reference' ]
  - fasta:
      type: fasta
      description: FASTA file
      pattern: "*.{fasta}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing reference information
        e.g. [ id:'reference' ]
  - db:
      type: db
      description: KMA database file
      pattern: "*.{db}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@Krannich479"
maintainers:
  - "@Krannich479"
