name: "FASTA_PROCESS_REFERENCE_ALL"
description: process and index a reference sequence
keywords:
  - fasta
  - reference
  - indexing
components:
  - samtools
  - bwa
  - biopython
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tools:
      type: string
      description: |
        Selection of used tools; options: [inv_prep_ref, samtools_faidx]
  - aligner:
      type: string
      description: |
        Chosen aligner. In case of bwa, an index file is generated
  - ref:
      type: file
      description: |
        FASTA file with the reference
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - preped_ref:
      type: file
      description: FASTA file containing the processed reference
      pattern: "*.{fasta/fa}"
  - fai:
      type: file
      description: FAI index file of the reference
      pattern: "*.{fai}"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@DimitriTernovoj"
maintainers:
  - "@DimitriTernovoj"