# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "FASTQ_QC_TRIMMING_ALL"
description: Container for raw read QC steps
keywords:
  - fastq
  - qc
components:
  - fastqc
  - fastp
input:
  - tools:
      type: string
      description: |
        Comma separated list of activated tools
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - trimmed_reads:
      type: file
      description: |
        Processed fastq files
  - multiqc_files:
      type: file
      description: List of files eligible for a MultiQC report
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@MarieLataretu"
maintainers:
  - "@MarieLataretu"
