---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "inv_top5references_r"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base==4.2.1
