name: "TOP5_REFERENCES"
description: Read a PAF file (INV sample-segmentDB alignment) and return the five best references in terms of number of residue matches
keywords:
  - references
  - reference
  - selection
  - influenza
  - top5

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - paf:
      type: file
      description: PAF file (alignment format)
      pattern: "*.paf"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - txt:
      type: file
      description: A subset (rows and columns) of the input PAF file, filtered for the top 5 alignments
      pattern: "*_best_refs.txt"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@krannich479"
maintainers:
  - "@krannich479"
